[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography", "algorithms"]
description = "Verifiable Secret Sharing Schemes for splitting, combining and verifying secret shares"
documentation = "https://docs.rs/vsss-rs-std"
edition = "2021"
homepage = "https://github.com/mikelodder7/vsss-rs-std"
keywords = ["crypto", "sharing", "secret", "verifiable"]
license = "Apache-2.0 OR MIT"
name = "vsss-rs-std"
readme = "README.md"
repository = "https://github.com/mikelodder7/vsss-rs-std"
version = "3.0.0-pre3"

[features]
default = ["curve25519"]
curve25519 = ["curve25519-dalek",  "sha2"]

[dependencies]
anyhow = "1.0"
curve25519-dalek = { version = "3", optional = true }
elliptic-curve = { version = "0.12", features = ["ecdh"] }
hex = "0.4"
rand_chacha = { version = "0.3", default-features = false }
rand_chacha_02 = { version = "0.2", package = "rand_chacha", default-features = false }
rand_core = "0.6"
serde = { version = "1.0", features = ["serde_derive"] }
sha2 = { version = "0.9", optional = true }
subtle = { version = "2.4" }
thiserror = "1.0"
uint-zigzag = { version = "0.2", features = ["std"] }
zeroize = { version = "1", features = ["zeroize_derive"] }

[dev-dependencies]
bls12_381_plus = "0.5.5"
ed25519-dalek = "1.0"
k256 = { version = "0.12", features = ["arithmetic", "bits"] }
p256 = { version = "0.11", features = ["arithmetic", "bits"] }
rand_7 = { version = "0.7", package = "rand" }
rand = "0.8"
rand_xorshift = "0.3"
serde_json = "1.0"
serde_bare = "0.5"
sha2 = "0.9"
x25519-dalek = "1.1"
